name: Use GH_PAT Secret

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issue
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Use the GH_PAT secret to create an issue
          curl -X POST -H "Authorization: token $GH_PAT" \
               -d '{"title":"New Issue Created by Workflow", "body":"This issue is created using a GitHub Actions workflow."}' \
               https://api.github.com/repos/${{ github.repository }}/issues
